version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    # with adaptations to use workspaces+projects instead of `uv pip`
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --all-extras
    - uv run sphinx-build -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/conf.py
